// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dtos "ml-mutant-test/dtos"

	mock "github.com/stretchr/testify/mock"

	utils "ml-mutant-test/utils"
)

// IntelligenceServiceInterface is an autogenerated mock type for the IntelligenceServiceInterface type
type IntelligenceServiceInterface struct {
	mock.Mock
}

// GetLocation provides a mock function with given fields: satellites
func (_m *IntelligenceServiceInterface) GetLocation(satellites []dtos.Satellites) (utils.Point, error) {
	ret := _m.Called(satellites)

	var r0 utils.Point
	if rf, ok := ret.Get(0).(func([]dtos.Satellites) utils.Point); ok {
		r0 = rf(satellites)
	} else {
		r0 = ret.Get(0).(utils.Point)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]dtos.Satellites) error); ok {
		r1 = rf(satellites)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessage provides a mock function with given fields: satellites
func (_m *IntelligenceServiceInterface) GetMessage(satellites []dtos.Satellites) string {
	ret := _m.Called(satellites)

	var r0 string
	if rf, ok := ret.Get(0).(func([]dtos.Satellites) string); ok {
		r0 = rf(satellites)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
